### ISSUE TITLE
Disable strict format

### ISSUE THREAD

**Issue by LukaSikic** [GrahamCampbell/Laravel-Markdown#115]
Can we somehow parse ##Title (without space in between)?

**Comment by colinodell** [comment]
Unfortunately that is not a [valid header per the CommonMark spec](https://spec.commonmark.org/0.28/#atx-headings):

> The opening sequence of # characters **must be followed by a space** or by the end of line.

You are welcome to override or replace the [ATXHeaderParser](https://github.com/thephpleague/commonmark/blob/0.18.0/src/Block/Parser/ATXHeadingParser.php#L36) so that it doesn't require a space; however, because this would violate the spec, we unfortunately won't be including this change in the main `league/commonmark` library.

Hope that helps answer your question!
