### ISSUE TITLE
Is the Service Provider writing to file?

### ISSUE THREAD

**Issue by jadjoubran** [GrahamCampbell/Laravel-Markdown#163]
**PHP version**: 7.4.26 (hint: `php --version`)

**Description**

Hi Graham, thanks for your work!

I discovered a weird issue that I was able to narrow down after 2 days to this package. I am trying to host a Laravel app on App Engine Standard, I've read on other issues that you don't work with it, in short, the limitation is that you can only write to the `/tmp` folder. This is something I've fixed. However, as soon as I install this package, it breaks with the following error when it's being auto discovered:

```
@php artisan package:discover --ansi

In Compiler.php line 36:

  Please provide a valid cache path.
```

The `Compiler.php` above is located in `Illuminate\View\Compilers`. Note that this is **not** an auto discovery issue as disabling it and then loading the `GrahamCampbell\Markdown\MarkdownServiceProvider` has the same issue.
So, this got me wondering, is your ServiceProvider attempting to write something into file?

If yes, I might be able to submit a fix.

**How to reproduce**
See above, not easy to reproduce

**Possible Solution**
Might be the possibility to provide an env variable so the user can change the writeable directory to `/tmp` or better yet, respect an overwritten storage path via `useStoragePath`. I can send a PR!

Thank you!

**Comment by GrahamCampbell** [comment]
~No, but you may have other code that does this, depending on what code you have or what packages you have loaded. Are you able to run this command in verbose mode, to show the stack trace?~

**Comment by GrahamCampbell** [comment]
Ohhhhhh, instantiating the compiler will do this. You need to set your env variable to write to tmp. This is a feature and not a bug... the framework makes sure the directory exists, precisely to support your use case (and the use case of people running on AWS Lambda). It'll auto-create the directory in tmp for you, so you don't run into crashes because it doesn't exist, but you do need to set the env variable so that the framework is able to create the directory in the correct place.

I use the following on AWS Lambda:

```
VIEW_COMPILED_PATH: /tmp/storage/framework/views
```
