### ISSUE TITLE
Could be worth having an interface

### ISSUE THREAD

**Issue by bedeMarkRadford** [GrahamCampbell/Laravel-Markdown#93]
I also prefer DI over Laravel Facades.

We have a use case where we would want to add a decorator depending on environment, so having an interface would solve that.

**Comment by GrahamCampbell** [comment]
You can dependency inject `League\CommonMark\Converter`. That is what the `Markdown` facade is calling under the hood: https://github.com/GrahamCampbell/Laravel-Markdown/blob/v8.1.0/src/MarkdownServiceProvider.php#L161-L177.

I am considering making an interface though, so that we can have htmlable output, thus solving (and replacing) https://github.com/GrahamCampbell/Laravel-Markdown/pull/96. I am still in two minds as to if this is needed, as it's easy to just pipe the output into an htmlstring yourself, as a programmer. In two minds if the converter should know about that, I kinda like it separate.
